workflow:
    - publish

shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test

    publish:
        steps:
            - install: npm install
            - publish: ./scripts/publish
        secrets:
            - NPM_TOKEN
            - GIT_TOKEN
