#! /bin/bash -e

echo "Adding new remote origin"
git remote add tagpusher https://${GIT_TOKEN}@github.com/screwdriver-cd/hashr.git

echo "Running npm publish"
ls
./scripts/npm-publish

echo "Pushing tags back to repo"
git push tagpusher --tags
