#!/bin/bash -e

if [ -z "$GIT_TOKEN" ] || [ -z "$NPM_TOKEN" ]; then
  echo Skipping publish in Pull Request
  exit 0
fi

# Setting up secrets
git remote set-url --push origin https://${GIT_TOKEN}@github.com/screwdriver-cd/hashr.git
npm config set access public > /dev/null 2>&1
npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} > /dev/null 2>&1

# Bump the version
npm run bump
# Publish the package
npm publish
# Push the new tag to GitHub
git push origin --tags -q
